### ISSUE TITLE
Documentation (for each function)

### ISSUE THREAD

**Issue by y248guo** [UBC-MDS/slimreda#34]

**Comment by thayeylolu** [comment]
@y248guo  I think we did this in milestone 3

**Comment by y248guo** [comment]
Hi, @thayeylolu I believe as in Milestone 4 we need to do the documentation for our R package (as we did in Milestone 3 for the Python package). It would be very similar but instead of adding it on the README file, we also need to add it on vignette as suggested by @khalidcawl :)
